/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIRMI;

import Controlers.MenuControler;
import javax.swing.*;

/**
 *
 * @author igork
 */
public class MenuGUI extends javax.swing.JFrame {
    private MenuControler controler;
    /**
     * Creates new form GUIPrivado
     */
    public MenuGUI() {
        controler = new MenuControler(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        txtServerNameMenu = new javax.swing.JTextField();
        txtUsernameMenu = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        txtServerIPMenu = new javax.swing.JTextField();
        lblServerName = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        lbluserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();
        lblLogInServer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        cmdConect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LogIn");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(60, 63, 65));
        background.setMaximumSize(new java.awt.Dimension(800, 500));
        background.setMinimumSize(new java.awt.Dimension(800, 500));
        background.setName(""); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setRequestFocusEnabled(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtServerNameMenu.setBackground(new java.awt.Color(255, 255, 255));
        txtServerNameMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtServerNameMenu.setForeground(new java.awt.Color(0, 0, 0));
        txtServerNameMenu.setToolTipText("Ingresar Usuario");
        txtServerNameMenu.setBorder(null);
        txtServerNameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServerNameMenuActionPerformed(evt);
            }
        });
        background.add(txtServerNameMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 250, 20));

        txtUsernameMenu.setBackground(new java.awt.Color(255, 255, 255));
        txtUsernameMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsernameMenu.setForeground(new java.awt.Color(0, 0, 0));
        txtUsernameMenu.setToolTipText("Ingresar Usuario");
        txtUsernameMenu.setBorder(null);
        txtUsernameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameMenuActionPerformed(evt);
            }
        });
        background.add(txtUsernameMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 250, 20));

        txtPort.setBackground(new java.awt.Color(255, 255, 255));
        txtPort.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPort.setForeground(new java.awt.Color(0, 0, 0));
        txtPort.setToolTipText("Ingresar Usuario");
        txtPort.setBorder(null);
        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });
        background.add(txtPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 250, 20));

        txtServerIPMenu.setBackground(new java.awt.Color(255, 255, 255));
        txtServerIPMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtServerIPMenu.setForeground(new java.awt.Color(0, 0, 0));
        txtServerIPMenu.setToolTipText("Ingresar Usuario");
        txtServerIPMenu.setBorder(null);
        txtServerIPMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServerIPMenuActionPerformed(evt);
            }
        });
        background.add(txtServerIPMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 250, 20));

        lblServerName.setBackground(new java.awt.Color(255, 255, 255));
        lblServerName.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblServerName.setForeground(new java.awt.Color(0, 0, 0));
        lblServerName.setText("Server Name");
        background.add(lblServerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        lblIP.setBackground(new java.awt.Color(255, 255, 255));
        lblIP.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIP.setForeground(new java.awt.Color(0, 0, 0));
        lblIP.setText("Server IP");
        background.add(lblIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        lblPort.setBackground(new java.awt.Color(255, 255, 255));
        lblPort.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblPort.setForeground(new java.awt.Color(0, 0, 0));
        lblPort.setText("Port");
        background.add(lblPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        lbluserName.setBackground(new java.awt.Color(255, 255, 255));
        lbluserName.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbluserName.setForeground(new java.awt.Color(0, 0, 0));
        lbluserName.setText("Username");
        background.add(lbluserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UFPS CHAT");
        jLabel1.setToolTipText("");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 260, 290, -1));

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIRMI/Images/logo.png"))); // NOI18N
        background.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 290, 150));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIRMI/Images/city.png"))); // NOI18N
        imgBackground.setMaximumSize(new java.awt.Dimension(800, 800));
        imgBackground.setMinimumSize(new java.awt.Dimension(800, 800));
        imgBackground.setPreferredSize(new java.awt.Dimension(800, 500));
        background.add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 300, -1));

        lblLogInServer.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblLogInServer.setForeground(new java.awt.Color(0, 0, 0));
        lblLogInServer.setText("LOG IN");
        background.add(lblLogInServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIRMI/Images/favicon.png"))); // NOI18N
        jLabel2.setText("RMI CHAT");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, 40));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 210, -1));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 210, -1));
        background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 210, -1));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 210, -1));

        cmdConect.setBackground(new java.awt.Color(51, 153, 255));
        cmdConect.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdConect.setForeground(new java.awt.Color(0, 0, 0));
        cmdConect.setText("CONECT");
        cmdConect.setBorder(null);
        cmdConect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdConect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConectActionPerformed(evt);
            }
        });
        background.add(cmdConect, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtPort() {
        return txtPort;
    }

    public void setTxtPort(JTextField txtPort) {
        this.txtPort = txtPort;
    }

    public JTextField getTxtServerIPMenu() {
        return txtServerIPMenu;
    }

    public void setTxtServerIPMenu(JTextField txtServerIPMenu) {
        this.txtServerIPMenu = txtServerIPMenu;
    }

    //GETTERS SETTERS
    
    
    public JTextField getTxtUsernameMenu() {
        return txtUsernameMenu;
    }

    public void setTxtUsernameMenu(JTextField txtUsernameMenu) {
        this.txtUsernameMenu = txtUsernameMenu;
    }

    public JTextField getTxtServerNameMenu() {
        return txtServerNameMenu;
    }

    public void setTxtServerNameMenu(JTextField txtServerNameMenu) {
        this.txtServerNameMenu = txtServerNameMenu;
    }

    public JTextField getTxtIPServerMenu() {
        return txtServerIPMenu;
    }

    public void setTxtIPServerMenu(JTextField txtIPServerMenu) {
        this.txtServerIPMenu = txtIPServerMenu;
    }

    private void txtUsernameMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameMenuActionPerformed

    private void cmdConectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConectActionPerformed
        // TODO add your handling code here:
        controler.conectToServer();
    }//GEN-LAST:event_cmdConectActionPerformed

    private void txtServerNameMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServerNameMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServerNameMenuActionPerformed

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void txtServerIPMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServerIPMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServerIPMenuActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cmdConect;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblLogInServer;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblServerName;
    private javax.swing.JLabel lbluserName;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtServerIPMenu;
    private javax.swing.JTextField txtServerNameMenu;
    private javax.swing.JTextField txtUsernameMenu;
    // End of variables declaration//GEN-END:variables
}
