/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIRMI;

import Controlers.ChatMenuControler;

import javax.swing.*;

/**
 *
 * @author LENOVO LOQ
 */
public class MenuChats extends javax.swing.JFrame  {
    private DefaultListModel model;
    ChatMenuControler controler;
    /**
     * Creates new form MenuChats
     */
    public MenuChats() {
        model = new DefaultListModel();
        controler = new ChatMenuControler(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstConectedUsers = new javax.swing.JList<>();
        lblLogo = new javax.swing.JLabel();
        cmdStartPrivateChat = new javax.swing.JButton();
        cmdStartPublicChat = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblImagebackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstConectedUsers.setBackground(new java.awt.Color(255, 255, 255));
        lstConectedUsers.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lstConectedUsers.setModel(model);
        jScrollPane1.setViewportView(lstConectedUsers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 250, 380));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIRMI/Images/logo.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        cmdStartPrivateChat.setBackground(new java.awt.Color(51, 153, 255));
        cmdStartPrivateChat.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdStartPrivateChat.setForeground(new java.awt.Color(0, 0, 0));
        cmdStartPrivateChat.setText("Chat Privado");
        cmdStartPrivateChat.setBorder(null);
        cmdStartPrivateChat.setBorderPainted(false);
        cmdStartPrivateChat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdStartPrivateChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStartPrivateChatActionPerformed(evt);
            }
        });
        jPanel1.add(cmdStartPrivateChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 100, 30));

        cmdStartPublicChat.setBackground(new java.awt.Color(51, 153, 255));
        cmdStartPublicChat.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdStartPublicChat.setForeground(new java.awt.Color(0, 0, 0));
        cmdStartPublicChat.setText("Chat Publico");
        cmdStartPublicChat.setBorder(null);
        cmdStartPublicChat.setBorderPainted(false);
        cmdStartPublicChat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdStartPublicChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStartPublicChatActionPerformed(evt);
            }
        });
        jPanel1.add(cmdStartPublicChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 100, 30));

        lblTitle.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("Lista de Usuarios Conectados");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblImagebackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIRMI/Images/city.png"))); // NOI18N
        jPanel1.add(lblImagebackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //GETTERS SETTERS

    public DefaultListModel getModel() {
        return model;
    }

    public void setModel(DefaultListModel model) {
        this.model = model;
    }

    public JList<String> getLstConectedUsers() {
        return lstConectedUsers;
    }

    public void setLstConectedUsers(JList<String> lstConectedUsers) {
        this.lstConectedUsers = lstConectedUsers;
    }
    
    
    private void cmdStartPrivateChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStartPrivateChatActionPerformed
        // TODO add your handling code here:
        controler.startPrivateChat();
    }//GEN-LAST:event_cmdStartPrivateChatActionPerformed

    private void cmdStartPublicChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStartPublicChatActionPerformed
        // TODO add your handling code here:
        controler.startPublicChat();
    }//GEN-LAST:event_cmdStartPublicChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuChats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuChats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuChats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuChats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuChats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdStartPrivateChat;
    private javax.swing.JButton cmdStartPublicChat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagebackground;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstConectedUsers;
    // End of variables declaration//GEN-END:variables
}
