/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIRMI;

import Controlers.PrivateChatControler;

import javax.swing.*;

/**
 *
 * @author igork
 */
public class PrivateChatGUI extends javax.swing.JFrame {
    private PrivateChatControler controler;
    private static PrivateChatGUI instance;
    /**
     * Creates new form GUIMenu
     */

    //APLICAMOS SINGLETON PARA QUE NO SE ABRAN VARIOS CHATS PRIVADOS A LA VEZ
    private PrivateChatGUI() {
        initComponents();
        controler = new PrivateChatControler(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public static PrivateChatGUI getInstance() {
        if (instance == null) {
            instance = new PrivateChatGUI();
        }
        return instance;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistory = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessagePrivateArea = new javax.swing.JTextArea();
        cmdSendMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHistory.setEditable(false);
        txtHistory.setColumns(20);
        txtHistory.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtHistory.setRows(5);
        jScrollPane1.setViewportView(txtHistory);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 580, 370));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("Historial Privado");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        lblUser.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblUser.setText("Usuario");
        background.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        txtMessagePrivateArea.setColumns(20);
        txtMessagePrivateArea.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtMessagePrivateArea.setRows(5);
        jScrollPane2.setViewportView(txtMessagePrivateArea);

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 580, -1));

        cmdSendMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIRMI/Images/SendMessageIcon.png"))); // NOI18N
        cmdSendMessage.setBorder(null);
        cmdSendMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSendMessageActionPerformed(evt);
            }
        });
        background.add(cmdSendMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSendMessageActionPerformed
        // TODO add your handling code here:
        controler.sendMessage();
    }//GEN-LAST:event_cmdSendMessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrivateChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrivateChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrivateChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrivateChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrivateChatGUI().setVisible(true);
            }
        });
    }

    //GETTERS SETTERS


    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }

    public JTextArea getTxtHistory() {
        return txtHistory;
    }

    public void setTxtHistory(JTextArea txtHistory) {
        this.txtHistory = txtHistory;
    }

    public JTextArea getTxtMessagePrivateArea() {
        return txtMessagePrivateArea;
    }

    public void setTxtMessagePrivateArea(JTextArea txtMessagePrivateArea) {
        this.txtMessagePrivateArea = txtMessagePrivateArea;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cmdSendMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextArea txtHistory;
    private javax.swing.JTextArea txtMessagePrivateArea;
    // End of variables declaration//GEN-END:variables
}
